services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - "127.0.0.1:3333:3001"
    restart: unless-stopped
    networks:
      - bear_caddy_net
      - uptime_kuma_net
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:3001" ]
      interval: 30s
      retries: 3
      start_period: 10s
networks:
  uptime_kuma_net:
    driver: bridge
  bear_caddy_net:
    external: true
